package org.processmining.plugins.inductiveVisualMiner.chain;

import org.processmining.plugins.inductiveVisualMiner.InductiveVisualMinerPanel;
import org.processmining.plugins.inductiveVisualMiner.configuration.InductiveVisualMinerConfiguration;

public abstract class DataChainLinkGuiAbstract extends DataChainLinkAbstract<InductiveVisualMinerConfiguration>
		implements DataChainLinkGui<InductiveVisualMinerConfiguration, InductiveVisualMinerPanel> {

}
